In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies = pd.read_csv("movies.csv")
rating = pd.read_csv("ratings.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
movies.shape

(9742, 3)

In [6]:
rating.shape

(100836, 4)

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [8]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [9]:
rating.describe()

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [10]:
movie_rating = movies.merge(
    rating,
    on="movieId"
)

In [11]:
movie_rating.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [12]:
avg_rating = movie_rating.groupby('title')['rating'].mean()
rating_count = movie_rating.groupby('title')['rating'].count()

In [13]:
popular_movies = pd.DataFrame({
    "average_rating": avg_rating,
    "rating_count": rating_count
})

popular_movies

                                           average_rating  rating_count
title
'71 (2014)                                       4.000000             1
'Hellboy': The Seeds of Creation (2004)          4.000000             1
'Round Midnight (1986)                           3.500000             2
'Salem's Lot (2004)                              5.000000             1
'Til There Was You (1997)                        4.000000             2
...                                                   ...           ...
eXistenZ (1999)                                  3.863636            22
xXx (2002)                                       2.770833            24
xXx: State of the Union (2005)                   2.000000             5
¡Three Amigos! (1986)                            3.134615            26
À nous la liberté (Freedom for Us) (1931)        1.000000             1

[9719 rows x 2 columns]

In [14]:
popular_movies = popular_movies.sort_values(
    by="average_rating",
    ascending=False
)
popular_movies

,average_rating,rating_count
title,,
Karlson Returns (1970),5.0,1
Zeitgeist: Moving Forward (2011),5.0,1
"Dream of Light (a.k.a. Quince Tree Sun, The) (Sol del membrillo, El) (1992)",5.0,1
Dragons: Gift of the Night Fury (2011),5.0,1
12 Angry Men (1997),5.0,1
...,...,...
The Pumaman (1980),0.5,1
3 dev adam (Three Giant Men) (1973),0.5,1
3 Ninjas Knuckle Up (1995),0.5,1
The Gracefield Incident (2015),0.5,1
Bloodsport: The Dark Kumite (1999),0.5,1

In [15]:
popular_movies = popular_movies[popular_movies["rating_count"] > 100]
popular_movies

                                  average_rating  rating_count
title
Shawshank Redemption, The (1994)        4.429022           317
Godfather, The (1972)                   4.289062           192
Fight Club (1999)                       4.272936           218
Godfather: Part II, The (1974)          4.259690           129
Departed, The (2006)                    4.252336           107
...                                          ...           ...
Net, The (1995)                         3.040179           112
Cliffhanger (1993)                      3.034653           101
Home Alone (1990)                       2.995690           116
Batman Forever (1995)                   2.916058           137
Waterworld (1995)                       2.913043           115

[134 rows x 2 columns]

In [16]:
popular_movies.sort_values(
    by='average_rating',
    ascending=False
).head(10)

                                           average_rating  rating_count
title
Shawshank Redemption, The (1994)                 4.429022           317
Godfather, The (1972)                            4.289062           192
Fight Club (1999)                                4.272936           218
Godfather: Part II, The (1974)                   4.259690           129
Departed, The (2006)                             4.252336           107
Goodfellas (1990)                                4.250000           126
Dark Knight, The (2008)                          4.238255           149
Usual Suspects, The (1995)                       4.237745           204
Princess Bride, The (1987)                       4.232394           142
Star Wars: Episode IV - A New Hope (1977)        4.231076           251

In [17]:
fig = px.scatter(
    popular_movies,
    x='rating_count',
    y='average_rating',
    hover_name= popular_movies.index,
    title="Movie Popularity VS Rating"
)

fig.show()

In [18]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [19]:
movies['genres'] = movies['genres'].fillna('')

In [20]:
cv = CountVectorizer(
    tokenizer= lambda x: x.split('|')
)

In [21]:
genre_matrix = cv.fit_transform(
    movies['genres']
)

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

In [22]:
similarity = cosine_similarity(
    genre_matrix
)

In [23]:
def recommendation(movies_name):

    idx = movies[
        movies['title'] == movies_name
    ].index[0]
    sim_scores = list(
        enumerate(similarity[idx])
    )
    sim_scores = sorted(
        sim_scores,
        key= lambda x: x[1],
        reverse=True
    )
    sim_scores = sim_scores[1:6]
    for movie in sim_scores:
        print(
            movies.iloc[
                movie[0]
            ]['title']
        )

In [24]:
recommendation('Toy Story (1995)')

Antz (1998)
Toy Story 2 (1999)
Adventures of Rocky and Bullwinkle, The (2000)
Emperor's New Groove, The (2000)
Monsters, Inc. (2001)

In [25]:
sample = similarity[:20, :20]

fig = px.imshow(
    sample,
    title="Movies Similarity Matrix"
)
fig.show()

In [26]:
movie_rating.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [27]:
user_movie_matrix = movie_rating.pivot_table(
    index= 'userId',
    columns= 'title',
    values= 'rating'
)
user_movie_matrix.shape

(610, 9719)

In [28]:
user_movie_matrix.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
user_movie_filled = user_movie_matrix.fillna(0)

In [30]:
user_movie_filled.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
user_similarity = cosine_similarity(user_movie_filled)

In [32]:
user_similarity_df = pd.DataFrame(
    user_similarity,
    index= user_movie_filled.index,
    columns=user_movie_filled.index
)

user_similarity_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [33]:
user_similarity_df[1].sort_values(
    ascending=False
).head(10)

userId
1      1.000000
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
Name: 1, dtype: float64

In [34]:
movie_user_matrix = movie_rating.pivot_table(
    index="title",
    columns="userId",
    values='rating'
)
movie_user_filled = movie_user_matrix.fillna(0)
movies_similarity = cosine_similarity(movie_user_filled)

In [35]:
movies_stats = movie_rating.groupby(
    'title'
).agg({
    'rating': ['mean', 'count']
})

In [36]:
movies_stats.head()

                                        rating
                                          mean count
title
'71 (2014)                                 4.0     1
'Hellboy': The Seeds of Creation (2004)    4.0     1
'Round Midnight (1986)                     3.5     2
'Salem's Lot (2004)                        5.0     1
'Til There Was You (1997)                  4.0     2

In [37]:
movies_stats.columns = [
    'avg_rating',
    'rating_count'
]
movies_stats.head()

                                         avg_rating  rating_count
title
'71 (2014)                                      4.0             1
'Hellboy': The Seeds of Creation (2004)         4.0             1
'Round Midnight (1986)                          3.5             2
'Salem's Lot (2004)                             5.0             1
'Til There Was You (1997)                       4.0             2

In [42]:
def recommend_movies(movie_name):

    if movie_name not in movies['title'].values:
        print("Movie not fount")
        return
    movie_idx = movies[
        movies['title'] == movie_name
    ].index[0]
    distances = similarity[movie_idx]
    
    movie_list = sorted(
        list(enumerate(distances)),
        
        reverse=True,

        key= lambda x: x[1]
    )[1:20]
    recommendation = []
    for i in movie_list:
        title = movies.iloc[
            i[0]
        ]['title']
        recommendation.append(
            title
        )
    return recommendation[:5]

In [44]:
recs = recommend_movies(
    'Toy Story (1995)'
)

for movie in recs:
    print(movie)

Antz (1998)
Toy Story 2 (1999)
Adventures of Rocky and Bullwinkle, The (2000)
Emperor's New Groove, The (2000)
Monsters, Inc. (2001)